// ch16/product-list/src/App.tsx
import React from 'react';
import './App.css';
import { CollectionView } from './CollectionView';
import { MyButton } from './MyButton';
import { Collection, IProduct } from './Products';
import { DetailView } from './DetailView';
import * as _ from 'underscore';
import { ajax } from 'rxjs/ajax';
import { CircularProgress } from "@material-ui/core";
import { MicroEventBus } from 'micro-event-bus';
export let microEventBus: MicroEventBus = (window as any).microEventBus;

export interface IAppProps { };
export interface IAppState {
  showDetails: boolean;
  product: IProduct | null;
  collectionInstance: Collection;
  username: string;
}

class App extends React.Component<IAppProps, IAppState> {
  constructor(props: IAppProps) {
    super(props);
    this.showDetailView = this.showDetailView.bind(this);
    this.handleClose = this.handleClose.bind(this);

    this.state = {
        showDetails: false,
        product: null,
        collectionInstance: new Collection(),
        username: "",
    }
  }

  componentDidMount() {
    this.processUserLoginEvent = this.processUserLoginEvent.bind(this);

    microEventBus.on('user-logged-in').subscribe(
        this.processUserLoginEvent
    );
    
    ajax.getJSON("http://127.0.0.1:3000/products")    
    //ajax.getJSON("https://gfd5mk0ob0.execute-api.us-east-1.amazonaws.com/Prod/products")
        .subscribe((data) => {
            let collection = new Collection();
            collection.items = data as IProduct[];
            this.setState({
                showDetails: false,
                product: null,
                collectionInstance: collection,
            });
        });
  }

  render() {
    return (
      <div>
        { this.state.collectionInstance.items.length < 1 ?
          <div className="App-header">
              <CircularProgress />
          </div>
          : ""}
        <CollectionView
          collections={this.state.collectionInstance}
          handleItemClicked={this.showDetailView} >
        </CollectionView>
        <DetailView open={this.state.showDetails}
                    product={this.state.product}
                    handleClose={this.handleClose}
                    username={this.state.username}>
        </DetailView>
      </div>

    )
  }
  handleClick() {
    console.log(`App.handleClick() called`);
    this.setState({
      showDetails: !this.state.showDetails
    })
  }

  showDetailView(id: number) {
    console.log(`App.handleClick() called`);
    let foundItem = _.find(
        this.state.collectionInstance.items,
        (item: IProduct) => {
            return item.id === id
        });

    if (foundItem) {
        this.setState({
            showDetails: true,
            product: foundItem
        });
    }
  }

  handleClose() {
      console.log(`App : handleClose()`);
      this.setState({
          showDetails: false,
          product: null
      })
  }

  processUserLoginEvent(event: string | undefined) {
    console.log(`RCT : App.processUserLoginEvent : ${event}`);

    if (event) {
        this.setState({ username: event });
    }
  }
}

export default App;

// ch16/shopping-cart/src/App.vue
<template>
   <div v-if="loading" class="loading">
      Loading...
    </div>
    <div v-if="!loading" class="loading">
      <ShoppingCart 
        :collection="cartItems" />
    </div>
</template>

<script lang="ts">
    import { Vue, Options } from 'vue-class-component';
    import { CartCollection, IProduct } from "./CartItems";
    import ShoppingCart from "./components/ShoppingCart.vue";
    import { MicroEventBus } from 'micro-event-bus';
    import { ajax } from "rxjs/ajax";
    export let microEventBus: MicroEventBus = (window as any).microEventBus;
    
    interface IItemData {
        username: string;
        productId: number;
        amount: string;
    }
    
    @Options({
        components: {
            ShoppingCart,
        },
        mounted() {
            console.log(`VUE: App:mounted()`);
            microEventBus.on('add-user-cart-item').subscribe(this.handleAddItemToCart);
            microEventBus.on('user-logged-in').subscribe(this.handleUserLoggedIn);
        }
    })
    export default class App extends Vue {
        cartItems!: CartCollection;
        username!: string;
        loading: boolean = false;
        data() {
            return {
                cartItems: new CartCollection(),
                username : null,
                loading: true
            }
        }
        handleUserLoggedIn(event: string) {
            console.log(`VUE: App.handleUserLoggedIn : ${event}`);
            this.username = event;
            this.loading = true;
            this.fetchData();
        }
    
        fetchData() {
            console.log(`calling ajax with ${this.username}`);
            ajax.getJSON(`http://127.0.0.1:3000/carts/${this.username}`).subscribe((data) => {
                console.log(`cart loaded from API`)
                let cartItems = new CartCollection();
                cartItems.items = <IProduct[]>data;
                this.cartItems = cartItems;
                this.loading = false;
            }, (error: any) => {
                console.log(`VUE: get /carts/(username) error : ${error}`);
                this.loading = false;
            }); 
        }
    
        handleAddItemToCart(data : IItemData) {
            console.log(`handleAddItemToCart : item : ${JSON.stringify(data)}`);
            console.log(`calling GET on /products/${data.productId}`);
            setTimeout(() => {
                this.loading = true;
                ajax.getJSON(`http://127.0.0.1:3000/products/${data.productId}`).subscribe((product) => {
                    let productItem = <IProduct>product;
                    productItem.amount = parseInt(data.amount);
                    this.cartItems.items.push(productItem);
                    this.loading = false;
                }, (error) => {
                    console.log(`VUE: products/${data.productId} : error ${error}`);
                }); 
    
            }, 200)
        }
    }
</script>

<style scoped>
</style>
